apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-hardy
spec:
  displayName: Hardy
  author:
    name: Hardy
    website: https://github.com/hardyz0517
  description: A clean, personal blog theme for Halo
  homepage: https://github.com/hardyz0517/theme-hardy#readme
  repo: https://github.com/hardyz0517/theme-hardy
  issues: https://github.com/hardyz0517/theme-hardy/issues
  settingName: "theme-hardy-setting"
  configMapName: "theme-hardy-configMap"
  version: 0.1.4
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/hardyz0517/theme-hardy/blob/main/LICENSE"
